### ISSUE TITLE
Is there a way so that reddit text formatting is applied through faces in the comment buffer?

### ISSUE THREAD

**Issue by Gira-X** [thanhvg/emacs-reddigg#4]
So text like 

```
`C-x C-o`
```

would be formatted with a face like `markdown-inline-code-face`.

Having the quote `>` character ported would also be great.

Turning on `markdown-mode` in the comment buffer in many cases delivers the expected result, it's just that it breaks the `outline-mode`. 

Maybe it could work by processing each comment starting in `markdown-mode' and then converting it to `org-mode` via Pandoc? But I suspect it will be very slow and probably overkill.

---

Here is the formatting help, just for reference:

![image](https://user-images.githubusercontent.com/15002298/134664972-6f2dd154-6ec9-4577-8b27-1d32d1d00f59.png)

**Comment by thanhvg** [comment]
I rarely see markdown usages on reddit content and when I see it for example when people show code snippets on on r/elisp the difference doesn't annoy me much. Probably I can add a feature to produce markdown mode buffer instead of org-mode. But markdown is really lame compared to org.

In the mean time as a work around we can surround only the post content with `#+begin_src markdown` and `#+end_src` then `org-mode` will display the surrounded content as `markdown`:

```
#+begin_src markdown
This text is ___really important___.
Try to put a blank line before...

> This is a blockquote

...and after a blockquote. 
Italicized text is the _cat's meow_.

A*cat*meow
Italicized text is the *cat's meow*.
#+end_src

```
We can write an elisp function to do it or we can use `org-insert-structure-template` as follows. First define the markdown template:
``` elisp
   (setq org-structure-template-alist
       '(("m" . "src markdown")))
;; if your `org-structure-template-alist` is ready set somewhere then use add-to-list
```
Once it is set, select the desired region and invoke `org-insert-structure-template`, then press `m`, done. You can bind  `org-insert-structure-template` to your own binding scheme.

**Comment by Gira-X** [comment]
I feel that the posts at https://old.reddit.com/r/emacs/ often use markdown and I just now have found a solution which works really well for me:

The idea is to initially generate a markdown text buffer and then convert it to `org-mode` via pandoc which works out really well. Here is how it ends up:

![image](https://user-images.githubusercontent.com/15002298/134871944-2d210a68-2c82-4049-bc10-96630c397877.png)

It works really well because the buffer is almost markdown anyway.

I had to advice some functions, for instance to change the `level` parameter from `*` to `#` and automatically invoke pandoc. I also display `OP` in case the author wrote a comment which I find nicer.
